config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :users
  get 'about', to: 'home#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  root 'contacts#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :contacts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def require_user
		redirect_to '/login' unless current_user
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :require_user, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.where('user_id': current_user.id)
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :socialLink, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #Hien trang chu
  def index
  end

  # Hien trang about us
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :verify_authenticity_token

	#Hien thi form dang nhap
	def new 
	end

	#Dang nhap
	def create
		@user = User.find_by_email(params[:session][:email])
		if @user && @user.authenticate(params[:session][:password])
			session[:user_id] = @user.id
			flash[:notice] = "Logged in successfully!"
			redirect_to root_path, allow_other_host: true
		else 
			flash[:notice] = "Invalid credentials"
			redirect_to '/login', allow_other_host: true
		end
	end

	#Dang xuat
	def destroy
		session[:user_id] = nil
		flash[:notice] = "You have been logged out!"
		redirect_to '/login'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :verify_authenticity_token 
	#Normally a Ruby on Rails app has Cross-Site Request Forgery (CSRF) protection. 
	#It should usually stay enabled, but for this practice project we need 
	#to disable it to ensure we can interact with the web app from the workspace browser correctly.

	# Hien thi form dang ky
	def new
		@user = User.new
	end

	# Luu thong tin dang ky vao db va dieu huong sang trang dang nhap
	def create
		@user = User.new(user_params)
  		@user2 = User.find_by(email: @user.email)

	  	if @user2
	    	flash[:notice] = 'This email is taken by another user'
	    	redirect_to '/signup'
	  	elsif @user.save
	    	flash[:success] = 'Registration successful. Please log in.'
	    	redirect_to '/login'
	    	puts 'success'
	  	else
	    	flash[:error] = 'Error creating user'
	    	redirect_to '/signup'
	    	puts 'error'
	  	end
	end

	private 
		def user_params
			params.require(:user).permit(:username, :email, :password)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_contact.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container bg-light p-5">
    <h1 class="display-4"><%= contact.name %></h1>
    <p class="lead"><strong>Email: </strong><%= contact.email %></p>
    <p class="lead"><strong>Phone number: </strong><%= contact.phone %></p>
    <p class="lead"><strong>Social: </strong><%= link_to contact.socialLink, contact.socialLink, target:"_blank" %></p>
  </div>
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>

  <div class="field form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone number" %>
  </div>

  <div class="field form-group">
    <%= form.label :socialLink, style: "display: block" %>
    <%= form.text_field :socialLink, class:"form-control", placeholder:"Social" %>
  </div>
  <div class="field form-group">
    <%= form.text_field :user_id, class:"form-control", placeholder:"User_Id", type: :hidden, value: current_user.id %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact, class:"btn btn-secondary mt-5" %>
  <%= link_to "Back to contacts", contacts_path, class:"btn btn-secondary mt-5" %>
</div>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<table class="table table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">STT</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone Number</th>
      <th scope="col">Social Link</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% count=1 %>
    <% @contacts.each do |contact| %>
      <tr>
        <th scope="row"><%= count %></th>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><a><%= contact.socialLink %><a/></td>
        <td><%= link_to "Show", contact %></td>
        <td><%= link_to "Edit", edit_contact_path(contact) %></td>
        <td><%= link_to "Delete", contact, method: :delete, data: { confirm: 'Are you sure? '} %></td>
      </tr>
      <% count += 1 %>
    <% end %>
  </tbody>
</table>
<%= link_to "New Contact", new_contact_path, class:"btn btn-primary" %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path, class:"btn btn-secondary" %>
</div>

app/views/contacts/show.html.erb
<%= render @contact %>

<div>
  <%= link_to "Edit this contact", edit_contact_path(@contact), class:"btn btn-secondary mt-5" %>
  <%= link_to "Back to contacts", contacts_path, class:"btn btn-secondary mt-5" %>
  <%= button_to "Destroy this contact", @contact, method: :delete, class:"btn btn-danger mt-5" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Contact Management', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Contacts', contacts_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'New Contact', new_contact_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'About us', about_path, class:"nav-link"%>
          </li>
      </ul>
    </div>
    <% if current_user %>
        <span class="text-capitalize text-info mr-3 font-italic">
          Hello, <%= current_user.username %>
        </span>
        <%= link_to 'Logout', logout_path %>
      <% end %>
  </div>
</nav>

app/views/home/about.html.erb
<h2>This is a demo app for our seminar presented by the following members.</h2>
<ol>
	<li class="fs-5">Lê Văn Phú</li>
	<li class="fs-5">Lê Hoài Hải</li>
	<li class="fs-5">Trần Tuấn Vũ</li>
	<li class="fs-5">Hoàng Phúc</li>
	<li class="fs-5">Ngô Trung Quân</li>
</ol>

app/views/home/index.html.erb
<h1 class="text-center">Contact Management App</h1>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close ml-auto" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_authForm.html.erb
<div class="d-flex justify-content-center align-items-center mt-5">
  <div class="card">
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
      <li class="nav-item text-center">
        <a class="nav-link active btl" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Login</a>
      </li>
      <li class="nav-item text-center">
        <a class="nav-link btr" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Signup</a>
      </li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
        <div class="form px-4 pt-5">
          <%= form_tag(login_path, method: "post") do %>
            <%= text_field_tag :email_or_phone, nil, class: "form-control", placeholder: "Email or Phone" %>
            <%= password_field_tag :password, nil, class: "form-control", placeholder: "Password" %>
            <%= submit_tag "Login", class: "btn btn-dark btn-block" %>
          <% end %>
        </div>
      </div>
      <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
        <div class="form px-4">
          <%= form_for :user, url: signup_path, method: "post" do |f| %>
            <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
            <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
            <%= f.text_field :phone, class: "form-control", placeholder: "Phone" %>
            <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
            <%= f.submit "Signup", class: "btn btn-dark btn-block" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contacts</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/header' %>
    <br><br/>
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alert' %>
      <% end %>
      <br><br/>
      <%= yield %>
    </div>
    <br><br/>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
  </body>
</html>

app/views/users/new.html.erb
<div class=”container”>
 <div class='row justify-content-center'>
   <div class=”col-5″>
     <div class=”mt-3″>
       <h1 class="text-center">Sign Up</h1>
     </div>
     <%= form_for(@user) do |form| %>
        <div class='form-group row mt-3'>
          <%= form.label :username %>
          <%= form.text_field :username, class: 'form-control',
                   :placeholder => 'Enter your username' %>
        </div>
        <div class='form-group row mt-3'>
          <%= form.label :email %>
          <%= form.email_field :email, class: 'form-control',
                                :placeholder => 'Enter your email' %>
        </div>
        <div class='form-group row mt-3'>
          <%= form.label :password %>
          <%= form.password_field :password, class: 'form-control',
                                :placeholder => 'Enter your password' %>
        </div>
        <div class='form-group row mt-3 d-flex justify-content-between'>
            <div class="align-items-center">
                <%= form.submit 'Create an Account', class: "btn btn-primary" %>
            </div>
            <div class="align-items-center">
                <%= link_to 'Login', login_path, class: "btn btn-secondary" %>
            </div>
        </div>
     <% end %>
   </div>
 </div>
</div>